name: Pytest
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: |
         python -m pip install --upgrade pip
         pip install pytest pytest-xvfb
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: |
         xvfb-run pytest 
